# -*- coding: utf-8 -*-
"""document_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlrx4ZhbOJSP7kJmuusCVlHZbVbsW3WL
"""

#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



!pip install groq

import groq

# Configure the Groq client with your API key.
# It's recommended to store your API key securely using Colab secrets.
# To do this, go to the '🔑' icon in the left panel, add a new secret,
# and name it 'GROQ_API_KEY'.
from google.colab import userdata

# Initialize the Groq client with the API key from Colab secrets
GROQ_API_KEY ='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'

class DocumentAnalyzerAgent:
    def __init__(self, model_name="llama3-8b-8192"):
        """Initializes the document analyzer agent with a Groq model."""
        self.model_name = model_name
        print(f"Document Analyzer Agent initialized with Groq model: {self.model_name}")

    def analyze_document(self, document_content: str, document_type: str = "general") -> dict:
        """Analyzes the provided document content based on its type using Groq.

        Args:
            document_content: The text content of the document.
            document_type: The type of the document (e.g., 'legal', 'finance', 'compliance', 'operations').

        Returns:
            A dictionary containing the analysis results.
        """
        prompt_messages = [
            {
                "role": "system",
                "content": f"You are an AI assistant specialized in analyzing {document_type} documents. Please analyze the following document and provide a summary, key points, potential risks/opportunities, and any specific insights relevant to {document_type}."
            },
            {
                "role": "user",
                "content": f"Document:\n{document_content}\n\nAnalysis:"
            }
        ]

        try:
            chat_completion = client.chat.completions.create(
                messages=prompt_messages,
                model=self.model_name,
                temperature=0.7,
                max_tokens=1024
            )
            return {"analysis": chat_completion.choices[0].message.content}
        except Exception as e:
            return {"error": str(e)}

    def run_analysis(self, documents: list[tuple[str, str]]) -> list[dict]:
        """Runs analysis on a list of documents.

        Args:
            documents: A list of tuples, where each tuple contains (document_content, document_type).

        Returns:
            A list of dictionaries, each containing the analysis result for a document.
        """
        results = []
        for content, doc_type in documents:
            print(f"Analyzing a {doc_type} document...")
            analysis = self.analyze_document(content, doc_type)
            results.append({"document_type": doc_type, "result": analysis})
        return results

# Example Usage (uncomment and replace with actual document content to test):
# if __name__ == "__main__":
#     # Make sure your GROQ_API_KEY is set in Colab secrets
#     agent = DocumentAnalyzerAgent()
#
#     sample_documents = [
#         ("This is a legal contract stating terms and conditions...", "legal"),
#         ("Financial report shows revenue of $10M and expenses of $8M...", "finance"),
#         ("Company policy on data privacy and GDPR compliance...", "compliance"),
#         ("Operational procedures for supply chain management...", "operations")
#     ]
#
#     # You would need to load your actual document content here
#     # For example, read from files or a database
#     # doc_content_legal = "..."
#     # doc_content_finance = "..."
#
#     # analysis_results = agent.run_analysis(sample_documents)
#
#     # for res in analysis_results:
#     #     print(f"\n--- {res['document_type'].upper()} DOCUMENT ANALYSIS ---")
#     #     print(res['result'].get('analysis', res['result'].get('error')))

